- extension/js/article-content.js
- src/js/util.js
- test/js/util-test.js
> ハッシュフラグメントつけると正常に登録されないバグを修正

- .travis.yml
> feat:support TravisCI

- gulpfile.js
- package.json
> feat:support-watch

- gulpfile.js
- package.json
> fix: gulp copyをcpxに変更

- src/assets/settings.html
- src/js/settings.js
- src/js/util.js
- test/js/util-test.js
> chore: 閲覧履歴の削除機能追加

- src/js/util.js
- test/js/util.spec.js
> fix: 非公開記事のparseに失敗する

- src/components/settings/extend.js
- src/components/settings/extend/auto-like.js
- src/components/settings/extend/show-line-number.js
- src/components/settings/thanks.js
- src/content_scripts/article-content.js
- src/content_scripts/article-list-stream-content.js
- src/content_scripts/article-list-stream/mute-user-article-list-stream-content.js
- src/content_scripts/article-list-tags-content.js
- src/content_scripts/article-list-tags/mute-user-article-list-tags-content.js
- src/content_scripts/article/auto-like-content.js
- src/content_scripts/article/mute-user-comment-content.js
- src/content_scripts/article/show-line-number-content.css
- src/content_scripts/article/show-line-number-content.js
- src/content_scripts/popular-items-content.js
- src/js/util.js
- src/manifest.json
- test/js/util.spec.js
> fix: 行番号を表示機能を追加

- src/content_scripts/article/article-content.js
- src/content_scripts/article/article-dom-handler.js
- src/content_scripts/article/auto-like-content.js
> fix: 自分が書いた記事でエラーが発生していたのを修正

- package.json
> chore: s/q-tool/q-accelerator/

- src/assets/popup.html
> fix: リンクのタイトルを要望から提案に変更する (#125)

- src/content_scripts/article/article-dom-handler.js
refactor: 使用していないfunctionを削除 #129
> refactor: 使用していないfunctionを削除 #129

- src/common/chrome-storage.js
- src/common/util.js
- test/common/util.spec.js
> fix: 未テストになっている部分のテストケースを追加 (#128)

- src/content_scripts/popular-items-content.js
- src/content_scripts/popular-items/show-already-read-button-content.js
> fix: 履歴オフにしても既読にするを押したときに履歴に残る #143

- package.json
- src/common/default-settings.json
- src/components/settings/extend.js
- src/components/settings/extend/show-stock-counts.js
- src/components/settings/thanks.js
- src/content_scripts/article-content.js
- src/content_scripts/article/article-dom-handler.js
- src/content_scripts/article/show-stock-counts-content.js
- test/content_scripts/article/article-dom-handler.spec.js
- yarn.lock
> feat: ストック数を見れるようにする (#152)

- package.json
- src/content_scripts/article/copy-code-content.js
- src/content_scripts/article/show-line-number-content.js
- webpack.config.js
- yarn.lock
> fix: webpackのバージョンを1から2に上げる (#163)

- docs/developers/usage-chrome-storage.md
- src/common/default-settings.json
- src/components/settings/extend.js
- src/components/settings/extend/show-articles-up-to-time.js
- src/content_scripts/article-content.js
- src/content_scripts/article/article-dom-handler.js
- src/content_scripts/article/show-articles-up-to-time-content.js
- test/content_scripts/article/article-dom-handler.spec.js
> feat: 記事の更新日を時間まで表示できるようにする (#158)

- src/content_scripts/article/article-dom-handler.js
> fix: 非推奨メソッドを推奨メソッドに変更(#167)

- src/content_scripts/article/article-dom-handler.js
- src/content_scripts/article/auto-like-content.js
MutationObserver経由に変更
Close #169
> fix: 自動いいね/自動ストックが機能していない #169

- src/content_scripts/article/article-dom-handler.js
Close #196 
以下 Chrome 69 のスクショ
> コメント数の数字とストックマークが被る問題を修正

- src/content_scripts/article/article-dom-handler.js
Close #04
- `100+`ならそのまま
- クリック時にストックされていたら -1
- クリック時にストックされていなかったら +1
> feat: ストックに合わせてストック数を加減させる
